export const STORAGE_KEYS = {
  ACCENT: "screenplay-reader-accent",
  LABEL_MODE: "screenplay-reader-label-mode",
  FOCUS_EFFECT: "screenplay-reader-focus-effect",
  FOCUS_CONTENT: "screenplay-reader-focus-content",
  HIGHLIGHT_CHAR: "screenplay-reader-highlight",
  HIGHLIGHT_SFX: "screenplay-reader-sfx",
  FONT_SIZE: "screenplay-reader-font-size",
  BODY_FONT: "screenplay-reader-body-font",
  DIALOGUE_FONT: "screenplay-reader-dialogue-font",
  READING_FONT: "screenplay-reader-reading-font",
  UI_FONT: "screenplay-reader-ui-font",
  DESKTOP_UI_SCALE: "screenplay-reader-desktop-ui-scale",
  EXPORT_MODE: "screenplay-reader-export-mode",
  LINE_HEIGHT: "screenplay-reader-line-height",
  SHOW_MARKERS: "screenplay-reader-show-markers",
  TRANSPARENT_BG: "screenplay-reader-transparent-bg",
  SHOW_UNDERLINE: "screenplay-reader-show-underline",
  USE_V2_RENDERER: "screenplay-reader-use-v2-renderer",
  V2_LAYOUT_CONFIG: "screenplay-reader-v2-layout-config",
};
