import { useMemo } from "react";

export function useScriptMetadataDetailsProps({
  status,
  coverUrl,
  setCoverUrl,
  currentTags,
  author,
  setAuthor,
  availableTags,
  newTagInput,
  setNewTagInput,
  targetAudience,
  handleSetTargetAudience,
  contentRating,
  handleSetContentRating,
  seriesName,
  setSeriesName,
  seriesId,
  setSeriesId,
  seriesOptions,
  quickSeriesName,
  setQuickSeriesName,
  handleQuickCreateSeries,
  isCreatingSeries,
  seriesOrder,
  setSeriesOrder,
  requiredErrorMap,
  handleAddTag,
  handleAddTagsBatch,
  handleRemoveTag,
  handleClearTags,
  contactFields,
  setContactFields,
  handleAddContactField,
  handleContactFieldUpdate,
  sensors,
  dragDisabled,
  setDragDisabled,
  customFields,
  setCustomFields,
  addCustomField,
  addDivider,
  handleCustomFieldUpdate,
  recommendedErrorMap,
}) {
  return useMemo(
    () => ({
      status,
      coverUrl,
      setCoverUrl,
      currentTags,
      author,
      setAuthor,
      availableTags,
      newTagInput,
      setNewTagInput,
      targetAudience,
      setTargetAudience: handleSetTargetAudience,
      contentRating,
      setContentRating: handleSetContentRating,
      seriesName,
      setSeriesName,
      seriesId,
      setSeriesId,
      seriesOptions,
      quickSeriesName,
      setQuickSeriesName,
      onQuickCreateSeries: handleQuickCreateSeries,
      isCreatingSeries,
      seriesOrder,
      setSeriesOrder,
      requiredErrors: requiredErrorMap,
      handleAddTag,
      handleAddTagsBatch,
      handleRemoveTag,
      handleClearTags,
      contactFields,
      setContactFields,
      onAddContactField: handleAddContactField,
      handleContactFieldUpdate,
      activeSensors: sensors,
      dragDisabled,
      setDragDisabled,
      customFields,
      setCustomFields,
      addCustomField,
      addDivider,
      handleCustomFieldUpdate,
      recommendedErrors: recommendedErrorMap,
      showStatusAlert: false,
      showAuthorCover: false,
      showAudienceRating: false,
      showSeries: false,
      showTags: false,
      layout: "stack",
    }),
    [
      status,
      coverUrl,
      setCoverUrl,
      currentTags,
      author,
      setAuthor,
      availableTags,
      newTagInput,
      setNewTagInput,
      targetAudience,
      handleSetTargetAudience,
      contentRating,
      handleSetContentRating,
      seriesName,
      setSeriesName,
      seriesId,
      setSeriesId,
      seriesOptions,
      quickSeriesName,
      setQuickSeriesName,
      handleQuickCreateSeries,
      isCreatingSeries,
      seriesOrder,
      setSeriesOrder,
      requiredErrorMap,
      handleAddTag,
      handleAddTagsBatch,
      handleRemoveTag,
      handleClearTags,
      contactFields,
      setContactFields,
      handleAddContactField,
      handleContactFieldUpdate,
      sensors,
      dragDisabled,
      setDragDisabled,
      customFields,
      setCustomFields,
      addCustomField,
      addDivider,
      handleCustomFieldUpdate,
      recommendedErrorMap,
    ]
  );
}
