import { useEffect } from "react";
import { normalizeActivityDemoLinks } from "../../lib/activityDemoLinks";

export function useScriptMetadataJsonPreview({
  script,
  title,
  author,
  authorDisplayMode,
  date,
  synopsis,
  outline,
  roleSetting,
  backgroundInfo,
  performanceInstruction,
  openingIntro,
  chapterSettings,
  activityName,
  activityBannerUrl,
  activityContent,
  activityDemoLinks,
  activityWorkUrl,
  contact,
  seriesName,
  seriesId,
  seriesOrder,
  coverUrl,
  status,
  licenseCommercial,
  licenseDerivative,
  licenseNotify,
  licenseSpecialTerms,
  copyright,
  identity,
  selectedOrgId,
  currentTags,
  contactFields,
  customFields,
  jsonMode,
  setJsonText,
}) {
  useEffect(() => {
    if (!script) return;
    const customObject = {};
    (customFields || []).forEach(({ key, value }) => {
      if (key) customObject[key] = value;
    });
    const contactObject = {};
    (contactFields || []).forEach(({ key, value }) => {
      if (key) contactObject[key] = value;
    });
    const payload = {
      title,
      credit: "",
      author,
      authorDisplayMode,
      authors: "",
      draftDate: date,
      synopsis,
      outline,
      roleSetting,
      backgroundInfo,
      performanceInstruction,
      openingIntro,
      chapterSettings,
      activityName,
      activityBannerUrl,
      activityContent,
      activityDemoLinks: normalizeActivityDemoLinks(activityDemoLinks).map(({ name, url, cast, description }) => ({
        name,
        url,
        cast,
        description,
      })),
      activityWorkUrl,
      contact,
      series: seriesName,
      seriesId,
      seriesOrder,
      cover: coverUrl,
      status,
      licenseCommercial,
      licenseDerivative,
      licenseNotify,
      licenseSpecialTerms,
      copyright,
      publishAs: identity,
      selectedOrgId: selectedOrgId || "",
      tags: (currentTags || []).map((tag) => ({ name: tag.name, color: tag.color })),
      contactFields: contactObject,
      custom: customObject,
    };
    setJsonText(JSON.stringify(payload, null, 2));
  }, [
    script,
    title,
    author,
    authorDisplayMode,
    date,
    synopsis,
    outline,
    roleSetting,
    backgroundInfo,
    performanceInstruction,
    openingIntro,
    chapterSettings,
    activityName,
    activityBannerUrl,
    activityContent,
    activityDemoLinks,
    activityWorkUrl,
    contact,
    seriesName,
    seriesId,
    seriesOrder,
    coverUrl,
    status,
    licenseCommercial,
    licenseDerivative,
    licenseNotify,
    licenseSpecialTerms,
    copyright,
    identity,
    selectedOrgId,
    currentTags,
    contactFields,
    customFields,
    jsonMode,
    setJsonText,
  ]);
}
